"""empty message

Revision ID: 3cd96db8604a
Revises: 
Create Date: 2025-05-26 11:12:17.165376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd96db8604a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GrLivArea', sa.Integer(), nullable=False),
    sa.Column('YearBuilt', sa.Integer(), nullable=False),
    sa.Column('GarageCars', sa.Integer(), nullable=False),
    sa.Column('TotalBsmtSF', sa.Integer(), nullable=False),
    sa.Column('FullBath', sa.Integer(), nullable=False),
    sa.Column('OverallQual', sa.Integer(), nullable=False),
    sa.Column('Neighborhood', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house')
    # ### end Alembic commands ###
